### ISSUE TITLE
it downloads the whole playlist

### ISSUE THREAD

**Issue by icha1** [cvzi/mpv-youtube-download#1]
Looks good! Thx. The only thing is that it downloads the whole playlist instead of just the current video.
Is it possible to add the youtube-dl archive option (--download-archive FILE  ) to avoid duplicate downloads?

**Comment by cvzi** [comment]
I added the option no-playlist (enabled by default) and an option to set a download archive, which you need to set

**Comment by icha1** [comment]
Great. Works perfect! Good job. Thanks a lot
