### ISSUE TITLE
[Question] How do I make a "bestvideo+bestaudio+allsubtitles" format?

### ISSUE THREAD

**Issue by WhoMI7** [cvzi/mpv-youtube-download#10]
How do I make a "bestvideo+bestaudio+allsubtitles" format and merge them in mkv container with a single keybind?

**Comment by cvzi** [comment]
You could create a text file somewhere with the yotube-dl config that you want. 
I create a text file here:  `C:\Users\cuzi\allsubs_config.txt`
and put this:
```bash
--format "bestvideo*+bestaudio/best"
--sub-format best
--all-subs
--write-sub
--embed-subs
--remux-video mkv
-o "C:\Users\cuzi\Downloads\%(title)s.%(ext)s"
```
(I don't know if this is the correct config for youtube-dl, you have to check in the youtube-dl documentation what the correct way to get all subtitles)

Then you can attach this text file to the keybind. Either change it in `youtube-download.lua` or in `youtube-download.conf`. For example to attach it to `CTRL+i` you need to change the value of `download_video_embed_subtitle_config_file` like this:
https://github.com/cvzi/mpv-youtube-download/blob/4c79abc40c24ba9a05d7e5fed1054e016b52d842/youtube-download.conf#L62
Remove the `#` in line 62 of youtube-download.conf and change the line to: 
```ini
download_video_embed_subtitle_config_file=C:\Users\cuzi\allsubs_config.txt
```

OR in `youtube-download.lua` change line 96
https://github.com/cvzi/mpv-youtube-download/blob/4c79abc40c24ba9a05d7e5fed1054e016b52d842/youtube-download.lua#L96 to
```lua
    download_video_embed_subtitle_config_file= "C:\\Users\\cuzi\\allsubs_config.txt",
```

**Comment by WhoMI7** [comment]
Thanks
