### ISSUE TITLE
Download_path problem

### ISSUE THREAD

**Issue by ma-zsola** [cvzi/mpv-youtube-download#14]
I usually copy multiple urls to the mpv playlist, then I download them separately with your script.

A few days ago I noticed the following weird behavior:

When I download the first item from the playlist, it works well.
When I select another item from the playlist, it creates a sub folder in the original download path as `E:\Downloads\E#\Downloads\...`.
If I select an additional item to download, it creates another sub folder in the newly added sub folder as `E:\Downloads\E#\Downloads\E#\Downloads\...`.

My setting:
```lua
download_path = "E:\\Downloads",
 ```

I use Win 11. mpv, ffmpeg and yt-dlp are all up-to-date. 
I "reinstalled" an old release of mpv and yt-dlp. I tried the feature without any other scripts in use. Unfortunetely, nothing helps.

**Comment by cvzi** [comment]
I will check it out

**Comment by cvzi** [comment]
This should fix it

**Comment by ma-zsola** [comment]
Thank you very much for the quick help, it's working!
