### ISSUE TITLE
[Feature Request]: Integrate this script with UOSC's menu

### ISSUE THREAD

**Issue by NaiveInvestigator** [cvzi/mpv-youtube-download#19]
Integrate youtube-download.lua with uosc's menus similiar to this script.
https://github.com/christoph-heinrich/mpv-quality-menu

I think it would an awesome feature to have. I hope you consider it!

**Comment by cvzi** [comment]
I am not familiar with UOSC at all, I'll see how difficult that is

**Comment by NaiveInvestigator** [comment]
I think this might help you then.

https://github.com/tomasklaen/uosc#message-handlers

**Comment by cvzi** [comment]
> https://github.com/tomasklaen/uosc#message-handlers

It seems relatively easy to add.

What did you have in mind for the menu?

**Comment by NaiveInvestigator** [comment]
oh it would just be used to like select the video and audio formats  to download just like with 
https://github.com/christoph-heinrich/mpv-quality-menu

Or I think wot would be better is that it should download the audio and video tracks i've selected only using mpv-quality-menu, but i'm not sure if that was already implemented or not. sorry to bother u if it was

**Comment by cvzi** [comment]
I guess the easiest would be to take the current format selected by quality-menu. Doesn't make much sense to implement the format selection again, if the quality-menu script does it better anyway. I think it can already use the format from quality-menu, or at least it used to work.

**Comment by cvzi** [comment]
So something like this maybe:

Download Menu:
*  Video current quality `mp4/720p`
*  Video default quality `best[height=1080]`
*  Audio current quality `mp3`
*  Audio default quality `bestaudio`
*  ... rest of the commands that the script support

So you have the option to download the current quality from quality-menu or the default quality defined in the config of this script

**Comment by NaiveInvestigator** [comment]
Yep! Sounds solid, looking forward to this update! 

Edit: Ty for considering this feature request!

**Comment by cvzi** [comment]
@tomasklaen 
I want to add an entry to the normal menu that opens a menu for downloading.
So I added a line to input.conf, something like this
```
#   script-message-to youtube_download show_menu    #! Download
```
Now that entry always appears in the menu. 
Is is possible to only show the entry, if a youtube url is being played? Can I add an entry to the menu programmatically (or hide it) instead of specifying it in the input.conf?

**Comment by tomasklaen** [comment]
No, main menu is static, so no API or optional items supported. I put stuff that is not needed often under Utils category:

```
#   script-message-to youtube_download show_menu    #! Utils > Download
```

**Comment by cvzi** [comment]
@tomasklaen Thanks!

**Comment by NaiveInvestigator** [comment]
> @tomasklaen I want to add an entry to the normal menu that opens a menu for downloading. So I added a line to input.conf, something like this
> 
> ```
> #   script-message-to youtube_download show_menu    #! Download
> ```
> 
> Now that entry always appears in the menu. Is is possible to only show the entry, if a youtube url is being played? Can I add an entry to the menu programmatically (or hide it) instead of specifying it in the input.conf?

we could add control buttons for each functions, and they can be added if a stream is being played or not. 
https://github.com/tomasklaen/uosc#set-prop-value

Control Buttons are like sort of like keybinds but instead of them being binded to a key, here they are binded to a button instead.
