### ISSUE TITLE
How to add cookie?

### ISSUE THREAD

**Issue by erickyun** [cvzi/mpv-youtube-download#2]
Hi,

I want first to Thank you for this awesome script.
And want to ask
How can I add this to youtube-download.lua
ytdl-raw-options=cookies="cookies.txt"

I want to know how can I add cookies to this script when downloading?

**Comment by cvzi** [comment]
~~I believe scripts cannot access the command line arguments~~ Edit: They can, see https://github.com/cvzi/mpv-youtube-download/blob/083fe4d2dc1690b5f8f1781c7203fd18861b71dc/youtube-download.lua#L71-L78

But I think it would be possible to hardcode it in the script. I will try that later

**Comment by erickyun** [comment]
> I believe scripts cannot access the command line arguments.
> 
> But I think it would be possible to hardcode it in the script. I will try that later

I did try myself to add this to mpv.conf but it didn't work.
ytdl-raw-options=cookies="cookies.txt


I will be waiting for you then. Thanks again. I Hope that it would be possible.

**Comment by cvzi** [comment]
I added an option to the script to set the cookie file. See [line 56 ](https://github.com/cvzi/mpv-youtube-download/blob/main/youtube-download.lua#L51-L56) in the script.

I didn't test it with a real cookie file though, because I don't have one. But if the file doesn't exist, it is created, so I assume it will work.

**Comment by erickyun** [comment]
> I added an option to the script to set the cookie file. See [line 56 ](https://github.com/cvzi/mpv-youtube-download/blob/main/youtube-download.lua#L51-L56) in the script.
> 
> I didn't test it with a real cookie file though, because I don't have one. But if the file doesn't exist, it is created, so I assume it will work.

You are a Hero :) Thank you very much for your work I did just test it. And it works. 

İf you have later time for it Could you maybe also think to include download subtitles in this script?

**Comment by cvzi** [comment]
I don't use subtitles myself.
Can subtitles be downloaded with youtube-dl?

**Comment by erickyun** [comment]
> I don't use subtitles myself.
> Can subtitles be downloaded with youtube-dl?

[Ytdl subtitle link](https://superuser.com/questions/927523/how-to-download-only-subtitles-of-videos-using-youtube-dl#:~:text=Subtitle%20Options%3A)

Yes it can be downloaded with **--sub-lang "en" --write-sub** you can also add **--skip-download** to only download subtitles there is also **--embed-subs** option to embed the subtitles to the video.

I think including only these two options like this seems sufficient.
-  To only download subtitles:
**--sub-lang "en" --write-sub --skip-download "crtl+s"**
And
-  To embed subtitles:
**--all-subs --write-sub --embed-subs "crtl+i"**

I did find [export subtitle](https://github.com/kelciour/mpv-scripts/blob/9a5cda4fc8f0896cec27dca60a32251009c0e9c5/sub-export.lua) script if it maybe will help you. But it doesn't work for external subtitles and it uses ffmpeg

**Comment by cvzi** [comment]
I implemented it as you suggested, ctrl+s and ctrl+i
Please test it and report if it works as expected

**Comment by erickyun** [comment]
> I implemented it as you suggested, ctrl+s and ctrl+i
> Please test it and report if it works as expected

You are the best thank you very much ☺️👍

Edit:
Just tested it work perfectly👍

**Comment by cvzi** [comment]
BTW here on github you can click the 👁Watch button at the top right next to the ☆ Star, then you will get an email when I update the script

**Comment by erickyun** [comment]
> BTW here on github you can click the 👁Watch button at the top right next to the ☆ Star, then you will get an email when I update the script

Ok thanks did click on it.

**Comment by erickyun** [comment]
Hi,

Me again😅 sorry if I distrub but could I ask for one last feature please.
Could I ask for feature that adds error.txt file when downloading videos? So that I can see the full log and know when error occurs.
cuz this specially happens with ffmpeg when downloading video files with segments. so could you add the 2> error.txt option for downloading videos?

So I was thinking:
For two download key binds ctrl+d and ctrl+i could they stay the same without being touched.But could you add error.txt with new key binds **ctrl+D , ctrl+İ** for the same commands that were in **ctrl+d and ctrl+i**?

Sorry for my bad English if I was not clear enough?

**Comment by cvzi** [comment]
I understand it 🙂 From which country are you?

I will check, I am not sure if it will work to just add 2> error.txt to the command in the script

**Comment by erickyun** [comment]
> I understand it 🙂 From which country are you?
> 
> I will check, I am not sure if it will work to just add 2> error.txt to the command in the script

I from turkey. 🙂

I Hope you will find a way and it will work.

**Comment by cvzi** [comment]
I have a request for you 😁
I develop an Android app: https://github.com/cvzi/ScreenshotTile 
and I am looking for people who can translate it. It is possible to translate it on this website: https://crwd.in/screenshottile
If you like to help, you can create a free account there and just translate as much as you want

**Comment by erickyun** [comment]
> I have a request for you 😁
> I develop an Android app: https://github.com/cvzi/ScreenshotTile
> and I am looking for people who can translate it. It is possible to translate it on this website: https://crwd.in/screenshottile
> If you like to help, you can create a free account there and just translate as much as you want

After all my request ofcourse I will do it ☺️ I will have look at it. 
I know also dutch I can help with translating that too.

**Comment by cvzi** [comment]
Thank you!

Dutch is not necessary, there is someone who is translating Dutch and he translates a few words every day and he will probably finish it in a few days.

----------

Just adding  `2>error.txt` to the command doesn't work. 
But the script can actually read the error output, so the script could display the error text on the video or write it to a error.txt file.
Do you have the output of youtube-dl when an error happened or can you copy it and post it the next time you see an error? Then I can see how these errors usually look like.

I don't think these errors happen for me often. The downloads seem to always work for me, but I only download short (music) videos.

**Comment by erickyun** [comment]
> Just adding `2>error.txt` to the command doesn't work.
> But the script can actually read the error output, so the script could display the error text on the video or write it to a error.txt file.
> Do you have the output of youtube-dl when an error happened or can you copy it and post it the next time you see an error? Then I can see how these errors usually look like.


Could you try to put a space like this **2> log.txt** or could you try this **>log.txt 2>&1** when I put this at the end of the command it gives me a full log text file. **Edit:** There also something like this for mpv 'log-file' = '~~/log.txt' don't know if it will help actually.

And I'm getting this error https://i.stack.imgur.com/X5H7V.jpg this error happens on ffmpeg downloading m3u8 video with segments.
I know from someone who told me that this error happens because of the site Im downloading a video from and that the only thing left to do is restart downloading cuz ffmpeg will skip that segment and merge full video without that segment so the video will be missing that segments duration.

**Comment by cvzi** [comment]
Yeah I tried with spaces and different combinations. I does work in the terminal for me as well, just not when I add it in the script.

I think I could change the script so it searches for "HTTP error" and "Failed to open segment" in the error output and if it finds that, it could show a message on the video or write an error message to a text file.

**Comment by erickyun** [comment]
> I think I could change the script so it searches for "HTTP error" and "Failed to open segment" in the error output and if it finds that, it could show a message on the video or write an error message to a text file.

İt would be better if it would add full log to the text file but for now Yes what you suggest could be great tentative solution for now. 🙂👍 

**Edit:**
Write a error to text file seems the best but would it also show which segment it fails?

**Comment by erickyun** [comment]
> > I think I could change the script so it searches for "HTTP error" and "Failed to open segment" in the error output and if it finds that, it could show a message on the video or write an error message to a text file.
> 
> İt would be better if it would add full log to the text file but Yes that could be great tentative solution for now. 🙂👍

**Edit:**
Write a error to text file seems the best but would it also show which segment it fails?

**Comment by cvzi** [comment]
If it can write to files then yes, it could write the full log to a file, exactly the same as 2> log.txt does in the terminal

I don't really know, I have to find out how to write to files in Lua programming language first, I don't actually have much experience with this programming language.

**Comment by erickyun** [comment]
> I don't really know, I have to find out how to write to files in Lua programming language first, I don't actually have much experience with this programming language.

I understand could you maybe try later then when you have time please?

> I think I could change the script so it searches for "HTTP error" and "Failed to open segment" in the error output and if it finds that, it could show a message on the video or write an error message to a text file.

And can you do both **"show a message on the video or write an error message to a text file."**
 so that I don't have to wait for download to finish and I can check text file if a error occurs?

**Comment by cvzi** [comment]
I will try when I have some time. 

Both yes, but I think the script can only see the error message when the download has finished.

**Comment by erickyun** [comment]
Many thanks for your help I really appreciate your work and after searching for so long I finally found the solution myself with setting key bind in the input.conf will do what I want. 🙂👍

**Edit:**
How did you get yt-dl to keep .ass subtitle format when using --embed-subs ?
When I try to use --embed-subs from PowerShell it converts .ass to .srt?
But your script doesn't convert it keep subtitle format.

**Comment by cvzi** [comment]
> **Edit2:**
> How did you get yt-dl to keep .ass subtitle format when using --embed-subs ?
> When I try to use --embed-subs from PowerShell it converts .ass to .srt?
> But your script doesn't convert it keep subtitle format.

This is the command the script executes:
`youtube-dl --all-subs --write-sub --embed-subs --sub-format best "https://example.com/video"`

**Comment by erickyun** [comment]
> > **Edit2:**
> > How did you get yt-dl to keep .ass subtitle format when using --embed-subs ?
> > When I try to use --embed-subs from PowerShell it converts .ass to .srt?
> > But your script doesn't convert it keep subtitle format.
> 
> This is the command the script executes:
> `youtube-dl --all-subs --write-sub --embed-subs --sub-format best "https://example.com/video"`

Thank you for your response I did find out it was known issue on ytdl.

I did a some translation here https://crwd.in/screenshottile will finish later

But can I one final request maybe?😅🙏
Could you add cookies to this script the author won't response to me?
[Link](https://github.com/jgreco/mpv-youtube-quality/blob/master/youtube-quality.lua)

**Comment by cvzi** [comment]
> I did a some translation here https://crwd.in/screenshottile will finish later

Thank you. Time doesn't matter, take as long as you need.

> But can I one final request maybe?😅🙏
> Could you add cookies to this script the author won't response to me?
> [Link](https://github.com/jgreco/mpv-youtube-quality/blob/master/youtube-quality.lua)

Yes I can do that. That script is actually the original one, my script is copied from it. That means I can probably just use the same code as in my script.

**Comment by erickyun** [comment]
> Yes I can do that. That script is actually the original one, my script is copied from it. That means I can probably just use the same code as in my script.

Yes Great I will be waiting 🙂

**Comment by cvzi** [comment]
This is the quality script: https://github.com/cvzi/mpv-youtube-quality/blob/add-cookies/youtube-quality.lua
It uses the command line argument, so if you do `mpv --ytdl-raw-options=cookies=cookies.txt ...` it should also use the cookies.txt or you can set it at the top of the script `cookies = "cookies.txt",` in the config like in this script.
Please test both

**Comment by erickyun** [comment]
> This is the quality script: https://github.com/cvzi/mpv-youtube-quality/blob/add-cookies/youtube-quality.lua
> It uses the command line argument, so if you do `mpv --ytdl-raw-options=cookies=cookies.txt ...` it should also use the cookies.txt or you can set it at the top of the script `cookies = "cookies.txt",` in the config like in this script.
> Please test both

I did test it work perfect. I dont know how many times I thanked you🙂 thanks men you're the best☺️👍

**Comment by cvzi** [comment]
The download script should now show errors on the video. Unfortunately it can only show the error message when the download is complete. Also I don't know how useful these error messages are, because the message in your screenshot is very long and it won't fit on the screen, but I cannot test it, because I don't get these errors.

When the download is complete and there were errors, it will write the errors to a log file. You need to set a log file in the script config
https://github.com/cvzi/mpv-youtube-download/blob/b7001623669a44484a208e75c2fa3c349c5ead7e/youtube-download.lua#L75-L80

**Comment by erickyun** [comment]
> The download script should now show errors on the video. 

That is awesome👍 

> Unfortunately it can only show the error message when the download is complete. Also I don't know how useful these error messages are,

it will be really useful cuz if it skip the segment when error occurs lets say if video duration 20mins it will go down to 10mins and so I know I must download from the beginning.
