### ISSUE TITLE
[Feature request] Auto-generated subtitles

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [cvzi/mpv-youtube-download#23]
Can you please add some option so I can download auto-generated subtitles from Youtube through the shortcut? For subtitles that are manually upload by the creator, it works just fine.

**Comment by cvzi** [comment]
Can yt-dlp download them? What's the command to do it?

**Comment by tXJtqlb3bbeKD1yW8SV7** [comment]
The documentation says it can. (https://github.com/yt-dlp/yt-dlp#subtitle-options)

**Comment by cvzi** [comment]
Yes I will add it

**Comment by tXJtqlb3bbeKD1yW8SV7** [comment]
Much appreciated.

**Comment by cvzi** [comment]
There's a new option now, that you can change to `true`

Either in the script:
https://github.com/cvzi/mpv-youtube-download/blob/fb37f1dd398cee72ffb6bf1c7c4bf92462bc9309/youtube-download.lua#L99
Or remove the `#` before `sub_auto_generated=true` in the config file:
https://github.com/cvzi/mpv-youtube-download/blob/fb37f1dd398cee72ffb6bf1c7c4bf92462bc9309/youtube-download.conf#L64-L75
