### ISSUE TITLE
[Feature request] Download all entries of the mpv playlist

### ISSUE THREAD

**Issue by ma-zsola** [cvzi/mpv-youtube-download#24]
Is there a way to download all entries of the mpv playlist at once with one keybind?

**Comment by cvzi** [comment]
I'll add it when I have some time, should be easy to do

**Comment by NaiveInvestigator** [comment]
you could try this script, this might be what you're looking for.

https://github.com/NaiveInvestigator/save-playlist

**Comment by ma-zsola** [comment]
> you could try this script, this might be what you're looking for.
> 
> https://github.com/NaiveInvestigator/save-playlist

Thank you for the suggestion, but in this particular case, this is not what I'm looking for.
Your script creates an m3u file from the mpv playlist.
I would like to download the videos from all urls on the mpv playlist at once, without opening them one by one.

**Comment by NaiveInvestigator** [comment]
>  I would like to download all urls from mpv playlist at once, without opening them one by one.

It does exactly that tho, m3u can also save urls. I also use that script daily for first putting all my to watch vids on mpv and then saving  the playlist. later on i just open the playlist and it plays those yt vids. 

I think you should try it first and then tell if any issues arise.

**Comment by cvzi** [comment]
You want to download the video file for each Youtube-url in the current mpv playlist?

And it's not a youtube playlist? Because Youtube playlists are supported with this option:
https://github.com/cvzi/mpv-youtube-download/blob/094a43f1da41e7c4a4800be1d0c3e0492f4ba3cd/youtube-download.lua#L57-L59

**Comment by ma-zsola** [comment]
> You want to download the video file for each Youtube-url in the current mpv playlist?

Yes, I would like to download the video file for each url from the current mpv playlist, not from the youtube playlist. 
Now, I can do this by selecting one url from the mpv playlist and run the script one by one to download the videos. 
Beside this I would like a function (if it is feasable) that can run the script for all entries of the mpv playlist, with only one keypress.

**Comment by cvzi** [comment]
Ok I understand, yes it definitely doable. I just didn't have time yet, too many other open-source projects 🤯

I can look at the code from NaiveInvestigator's script to see how to get all the urls from the mpv playlist, and then just queue all urls for downloading.
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by ma-zsola** [comment]
Thank you :-)

**Comment by cvzi** [comment]
There is now a new option in the conf to enable downloading the mpv playlist:
https://github.com/cvzi/mpv-youtube-download/blob/cce0080feb8f7f2cfecdb9b695e9d61712615aac/youtube-download.lua#L62-L64

Also you can set a keyboard shortcut to toggle the mode:
https://github.com/cvzi/mpv-youtube-download/blob/cce0080feb8f7f2cfecdb9b695e9d61712615aac/youtube-download.lua#L24
For example you could set this to "ctrl+p" and then you would need to press "ctrl+p" to enable the "playlist mode" and then "ctrl+d" to start downloading the playlist.

**Comment by ma-zsola** [comment]
Thank you very much, it works great.
I experienced just one strange thing: When I set `open_new_terminal` to true value, I have to press "ctrl+d" multiple times to download all the entries one by one.

**Comment by cvzi** [comment]
I forgot about that option.
That's a problem because the script cannot know when the first download has finished. I guess it would need to start all the downloads at the same time.

**Comment by ma-zsola** [comment]
> I guess it would need to start all the downloads at the same time.

That would be great.

**Comment by cvzi** [comment]
Starting all downloads at once doesn't work. There seems to be a bug in Windows Terminal if you open too many tabs at once.

I added a setting `open_new_terminal_timeout` to the conf. It is set to 3 seconds, meaning it will start the second download after 3 seconds the third after 6 seconds the fourth after 9 seconds ...

**Comment by ma-zsola** [comment]
It's working great. :-) 
Thank you very much for the help.

**Comment by NaiveInvestigator** [comment]
could we add a `download_mpv_playlist` entry for the uosc download menu too since there is already a keybind for it

edit: fixed grammar

**Comment by cvzi** [comment]
I've added an entry, doesn't it show up for you?

**Comment by NaiveInvestigator** [comment]
mb i didnt update lol, now it there lol! sorry for disturbing you :<<
