### ISSUE TITLE
can this also download video other than youtube??

### ISSUE THREAD

**Issue by firefoxOnFire** [cvzi/mpv-youtube-download#26]
I use mpv to stream video from direct url of video other than youtube. Can this also download those video while watching??

**Comment by cvzi** [comment]
Have you tried it? Is there an error message appearing? 

The script uses the yt-dlp tool to download and I think yt-dlp supports direct url as well.
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by firefoxOnFire** [comment]
> Have you tried it? Is there an error message appearing? The script uses the yt-dlp tool to download and I think yt-dlp supports direct url as well. -- Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

sorry for early issues...actually right now configuring yt-dlp in my machine.
