### ISSUE TITLE
[Feature request] Download from specific time

### ISSUE THREAD

**Issue by erickyun** [cvzi/mpv-youtube-download#3]
İt would be awesome if you Could maybe add key bind to download youtube videos at specific time only. so that I don't have to download whole video when I prefer?

**Comment by cvzi** [comment]
Can `youtube-dl` download from a specific time? What is the command?

**Comment by erickyun** [comment]
> Can `youtube-dl` download from a specific time? What is the command?

Youtube-dl can make ffmpeg cut the video without having to download whole video.

I don't know which command it relevant so I will write them all.
Something like this:

`youtube-dl --postprocessor-args "-ss 15 -t 20" '[video_URL]' `
but this one requires to download whole video so it is not ideal 

[Link for the commands](https://unix.stackexchange.com/questions/230481/how-to-download-portion-of-video-with-youtube-dl-command#:~:text=youtube-dl%20--youtube-skip-dash-manifest%20-g%20%22URL%22)

Or

**This one is best and simpleone I think.**

`youtube-dl 'URL' --external-downloader ffmpeg --external-downloader-args '-ss 20 -t 20'`

Or

`ffmpeg -ss 20 -i $(youtube-dl -g "URL" -f best) -c copy -t 40 output.mkv`


İf it maybe will help you I found other script that cuts video only for local videos.

[Cut-video.lua](https://github.com/samhippo/mpv-scripts/blob/master/cut-video.lua)
İf you could do something like **cut-video.lua** it would be great.🙂👍

[sub-cut.lua](https://github.com/kelciour/mpv-scripts/blob/master/sub-cut.lua)

**Comment by cvzi** [comment]
Yeah when I have some time I'll add it. cut-video.lua seems good with the arrow keys

I think it would be nice like this:

1. `ctrl + r` to activate this mode
2. Default cut range: from current time until end
3. Arrow keys to change the cut range (like _cut-video.lua_)
3. Start download with one of the normal combinations ctrl+d / ctrl+a / ctrl+s / ctrl+i

**Comment by erickyun** [comment]
> Yeah when I have some time I'll add it. cut-video.lua seems good with the arrow keys
> 
> I think it would be nice like this:
> 
> 1. `ctrl + r` to activate this mode
> 2. Default cut range: from current time until end
> 3. Arrow keys to change the cut range (like _cut-video.lua_)
> 4. Start download with one of the normal combinations ctrl+d / ctrl+a / ctrl+s / ctrl+i

That would be awesome I can't wait for it. 🙂👍

**Comment by cvzi** [comment]
It should work like this now:
1. `ctrl + r` to activate the "select mode"
2. Default cut range: from current time until end
3. Arrow keys to change the cut range (like _cut-video.lua_)
4. (Optional: Press `ctrl + r` again and then you can select second by second with the arrow keys)
5. Start download with one of the normal combinations ctrl+d / ctrl+a / ctrl+s / ctrl+i

**Comment by erickyun** [comment]
Thank you very much for this awesome script :)

**Comment by erickyun** [comment]
I noticed some bug video and audio are out of sync?

video plays but there is no sound or video ends but I hear audio playing in background.

**Edit:**
I think I found the problem it is ytdl. [Link](https://github.com/ytdl-org/youtube-dl/pull/16571#:~:text=For%20example%2C%20ffmpeg%20will%20refuse%20-to%20in%20the%20args%20without%20this%20patch.%20And%20it%20won%27t%20stop%20downloading%20after%20downloading%20the%20specified%20duration%20if%20given%20-ss%20START_TIME%20-t%20DURATION%20without%20this%20patch.%20Both%20happen%20because%20-t%20and%20-to%20%28and%20-fs%29%20need%20to%20come%20after%20the%20input%20%28i.e.%2C%20before%20the%20output%29.)

## Edit2:

I think This command should work without any problem since this time the url will directly be send to ffmpeg. And This So sad btw☹️ the script looked so good. 😩 

```
ffmpeg -ss 20 -i $(youtube-dl -g "${path}" -f bestvideo) -c copy -t 40 vid.mp4 && ffmpeg -ss 20 -i $(youtube-dl -g "${path}" -f bestaudio) -c copy -t 40 aud.m4a && ffmpeg -i vid.mp4 -i aud.m4a -c copy final.mkv
```

**Comment by erickyun** [comment]
so I did build [.exe](https://mega.nz/file/TkhBWShJ#AyPaCRZIbiVLmXn3VTrehtM1WstXqVDw-_0FB9mYyZM) file with  [external.py](https://github.com/ytdl-org/youtube-dl/blob/71d5459c0b33e0ae8fa4d42b90e5a849373e0e12/youtube_dl/downloader/external.py) but now I think the problem is your command -ss is fine it must be placed before the URL but **-to** is the problem here -to must come after URL

**Comment by cvzi** [comment]
The problem is that youtube-dl (by default) downloads the video and the audio separately and then combines the video file and the audio file into one file. 
~~If the files are downloaded separately than they will never be perfectly the same length and if they are not perfectly the same length, then it will be out of sync.~~

If you specify a format that is served as a single file by youtube then it works fine

Example that cuts 60 seconds from 120s to 180s:
**Works:**  (because single file)
*   `youtube-dl -f 22 --external-downloader ffmpeg --external-downloader-args "-ss 120 -to 180" https://www.youtube.com/watch?v=kcGYk2OWQkY`
*   `youtube-dl -f best --external-downloader ffmpeg --external-downloader-args "-ss 120 -to 180" https://www.youtube.com/watch?v=kcGYk2OWQkY`

**Out of sync:** (because bestaudio and bestvideo are seperate urls/files)

*   `youtube-dl --external-downloader ffmpeg --external-downloader-args "-ss 120 -to 180" https://www.youtube.com/watch?v=kcGYk2OWQkY`
*   `youtube-dl -f "bestvideo+bestaudio" --external-downloader ffmpeg --external-downloader-args "-ss 120 -to 180" https://www.youtube.com/watch?v=kcGYk2OWQkY`


After reading https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection
it seems 1080p is not offered as a single file by youtube.

I see two solutions:

The simple solution for 1080p (or higher) would be to download the **complete** video and **complete** audio separately, merge them and then **cut it afterwards**. 

The correct solution would be to download the video and audio parts separately with -ss -to, then cut the downloaded files so they are perfectly the same, then merge them together. I am not sure how difficult that or if it is even possible


I don't think the merge request about -to after the url is correct. Maybe it is for an old version of ffmpeg.

**Comment by erickyun** [comment]
> The correct solution would be to download the video and audio parts separately with -ss -to, then cut the downloaded files so they are perfectly the same, then merge them together. I am not sure how difficult that or if it is even possible


İt would be great if the second one would work🙂

Do you think this command would work maybe?
```
ffmpeg -ss 20 -i $(youtube-dl -g "${path}" -f bestvideo) -c copy -t 40 vid.mp4 && ffmpeg -ss 20 -i $(youtube-dl -g "${path}" -f bestaudio) -c copy -t 40 aud.m4a && ffmpeg -i vid.mp4 -i aud.m4a -c copy final.mkv
```

**Comment by erickyun** [comment]
> The simple solution for 1080p (or higher) would be to download the **complete** video and **complete** audio separately, merge them and then **cut it afterwards**.

I think this command will do that 
```
youtube-dl 'URL' --postprocessor-args "-ss 15 -t 20"
```

İf I'm right then?
İn the **script** Simply replacing **--external-downloader-args** with **--postprocessor-args** would fix it.

But if you could it would be nice if you could make the  **second solution** work.

**Comment by cvzi** [comment]
> Do you think this command would work maybe?
> 
> ```
> ffmpeg -ss 20 -i $(youtube-dl -g "${path}" -f bestvideo) -c copy -t 40 vid.mp4 && ffmpeg -ss 20 -i $(youtube-dl -g "${path}" -f bestaudio) -c copy -t 40 aud.m4a && ffmpeg -i vid.mp4 -i aud.m4a -c copy final.mkv
> ```

Probably not, because it also creates two files, so the same problem.

Maybe we can put it in one command something like this:
```
ffmpeg -y -ss 20 -to 40 -i $(youtube-dl -g URL -f bestvideo) -ss 20 -to 40 -i $(youtube-dl -g URL -f bestaudio) -c copy out.mkv
```
Not sure if that is possible with ffmpeg like that, but I think it should be possible to specify multiple inputs for ffmpeg.
I will test it later when I am on my computer.

**Comment by erickyun** [comment]
> > Do you think this command would work maybe?
> > ```
> > ffmpeg -ss 20 -i $(youtube-dl -g "${path}" -f bestvideo) -c copy -t 40 vid.mp4 && ffmpeg -ss 20 -i $(youtube-dl -g "${path}" -f bestaudio) -c copy -t 40 aud.m4a && ffmpeg -i vid.mp4 -i aud.m4a -c copy final.mkv
> > ```
> 
> Probably not, because it also creates two files, so the same problem. 

İt creates one **vid.mp4** and one **aud.m4a** and then it merges with this command: `ffmpeg -i vid.mp4 -i aud.m4a -c copy final.mkv` normally written in PowerShell should work but I don't know about scripts?

> Maybe we can put it in one command something like this:
> 
> ```
> ffmpeg -y -ss 20 -to 40 -i $(youtube-dl -g URL -f bestvideo) -ss 20 -to 40 -i $(youtube-dl -g URL -f bestaudio) -c copy out.mkv
> ```
> 
> Not sure if that is possible with ffmpeg like that, but I think it should be possible to specify multiple inputs for ffmpeg.
> I will test it later when I am on my computer.

**-to** needs to come after **-i**
So it needs to be something like this:
```
ffmpeg -y -ss 20 -i $(youtube-dl -g URL -f bestvideo) -to 40 -ss 20 -i $(youtube-dl -g URL -f bestaudio) -to 40 -c copy out.mkv
```

**Comment by erickyun** [comment]
> ```
> ffmpeg -y -ss 20 -to 40 -i $(youtube-dl -g URL -f bestvideo) -ss 20 -to 40 -i $(youtube-dl -g URL -f bestaudio) -c copy out.mkv
> ```

> I will test it later when I am on my computer.

it seems to work I did test it

**Comment by cvzi** [comment]
Yes both work for me as well. Then it will work in the script as well. Scripts cannot do && and ${..} but that can be solved by running the commands separately. I tested it with every command separately and it works also. Like this:
```sh
youtube-dl -g URL -f bestvideo   # returns video file url
youtube-dl -g URL -f bestaudio   # returns audio file url
ffmpeg -ss 20 -t 40  -i "returned url from first command" -c copy vid.mp4
ffmpeg -ss 20 -t 40  -i "returned url from second command" -c copy aud.m4a
ffmpeg -i vid.mp4 -i aud.m4a -c copy final.mkv
```
So the separate files were never the issue 😐

This is actually the same as what youtube-dl with --external-downloader-args does internally.
The difference between this solution and youtube-dl is that youtube-dl uses `vid.webm` instead of `vid.mp4`
When I replace `.mp4` with `.webm` in the above commands, than the video is out of sync as well. So that seems to be the problem. I don't know if it is a problem with ffmpeg not handling webm correctly or if youtube-dl is incorrectly using webm 🤔 

Anyway, to make it work in the script, I need to rewrite the download function in the script because it is a completely different command from the normal download now. So that will take some time.

> **-t** needs to come after **-i**

I checked that and it's not necessary. With the current ffmpeg version, that I used (version 4.3.2-2021-02-27), -t can be before or after -i, doesn't matter, -to **must be before** -i. 
I believe that merge request for external.py is no longer correct. It is from 2018, probably ffmpeg has changed since then.

**Comment by erickyun** [comment]
> The difference between this solution and youtube-dl is that youtube-dl uses `vid.webm` instead of `vid.mp4`
> When I replace `.mp4` with `.webm` in the above commands, than the video is out of sync as well. So that seems to be the problem. I don't know if it is a problem with ffmpeg not handling webm correctly or if youtube-dl is incorrectly using webm 🤔

Maybe this will work then?
bestvideo[ext*=mp4]+bestaudio[ext*=m4a]/best[ext*=mp4]/best

[Link1](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection#:~:text=%2A%3D%20%28contains%29)
[Link2](https://stackoverflow.com/questions/31631535/youtube-dl-dash-video-and-audio-in-highest-quality-without-human-intervention#:~:text=If%20you%20wanted%20to%20prefer%20MP4%20format%20containers%20instead%20of%20WebM%2C%20use%3A)

**Comment by cvzi** [comment]
> Maybe this will work then?
> bestvideo[ext*=mp4]+bestaudio[ext*=m4a]/best[ext*=mp4]/best
> 
I tested with two video, and seems to work.
I'll put it in the script then we can test it.

**Comment by cvzi** [comment]
Try this: https://github.com/cvzi/mpv-youtube-download/blob/timerange2/youtube-download.lua

**Comment by erickyun** [comment]
> Try this: https://github.com/cvzi/mpv-youtube-download/blob/timerange2/youtube-download.lua

Sadly:( didn't also work.

The audio won't be cutted video ends but I hear audio playing

**Comment by cvzi** [comment]
Is it out of sync as well or just at the end the audio is too long?

**Comment by erickyun** [comment]
> Is it out of sync as well or just at the end the audio is too long?

The audio is too long and video doesn't play right.

**Comment by cvzi** [comment]
It works for me, I tested it with a few videos now.

Did you/can you test the other version:
https://github.com/cvzi/mpv-youtube-download/blob/timerange/youtube-download.lua
That is the version that uses `ffmpeg -y -ss 20 -to 40 -i $(youtube-dl -g URL -f bestvideo) -ss 20 -to 40 -i $(youtube-dl -g URL -f bestaudio) -c copy out.mkv`
It currently always downloads to filename "out.mkv"

**Comment by cvzi** [comment]
Could you also try if it helps to run this command on one of the broken files:
```sh
ffmpeg -i "[brokenvideo]" -c copy "out.mkv"
```
That just unpacks and repacks the video and audio, but maybe it will also fix errors.

**Comment by cvzi** [comment]
Could you also try if it helps to run this command on one of the broken files:
```sh
ffmpeg -i "[brokenvideo]" -c copy "newfile.mkv"
```
That just unpacks and repacks the video and audio, but maybe it will also fix errors.

**Comment by erickyun** [comment]
> It works for me, I tested it with a few videos now.
> 
> Did you/can you test the other version:
> https://github.com/cvzi/mpv-youtube-download/blob/timerange/youtube-download.lua
> That is the version that uses `ffmpeg -y -ss 20 -to 40 -i $(youtube-dl -g URL -f bestvideo) -ss 20 -to 40 -i $(youtube-dl -g URL -f bestaudio) -c copy out.mkv`
> It currently always downloads to filename "out.mkv"

I noticed with **mpc player** the video never starts from 00:00:00 it starts from 00:00:02 but this [download.lua](https://github.com/cvzi/mpv-youtube-download/blob/timerange/youtube-download.lua) version works without other problems

with **mpv** the video starts from 00:00:00 but the problem is at the beginning video lags or screen freezes for 1 second and then it turns normal at 00:00:02 

with **mpc player** there is no freezing
But like I said it never start at 00:00:00

I think I will close the issue and thank you very much for your hard work I really appreciated it.
Cuz I see the command is right Maybe mpv is the problem what do you use when watching **out.mkv** ?
For now I will try watching with other players.

**Comment by cvzi** [comment]
Can you try to cut the first 2 seconds of a downloaded file like this:
```
ffmpeg -ss 2 -i "[brokenvideo]" -c copy "newfile.mkv"
```
If it helps, and it then plays normal, the script could always download 2 seconds earlier and then cut the 2 seconds again.

Edit:
Oh yes with mpv it lags for me as well, I used VLC earlier.

Edit2: 
2 seconds doesn't help, but 4 seconds helps for me:
```
ffmpeg -ss 4 -i "[brokenvideo]" -c copy "newfile.mkv"
```

I think the problem is that video cannot be cut precisely, because the compression of the video only allows to cut at certain points (in our case maybe every 2 seconds). If you want to cut a video precisely you need to re-encode it.

**Comment by erickyun** [comment]
> Can you try to cut the first 2 seconds of a downloaded file like this:
> 
> ```
> ffmpeg -ss 2 -i "[brokenvideo]" -c copy "newfile.mkv"
> ```
> 
> If it helps, and it then plays normal, the script could always download 2 seconds earlier and then cut the 2 seconds again.
> 
> Edit:
> Oh yes with mpv it lags for me as well, I used VLC earlier.

Not -ss 2 but with -ss 3 did solved the problem for mpv too. -ss 2 did do nothing it didn't even cut the video but -ss 3 did cut the video and fix the problem.

And also ffmpeg did give [this warning](https://i.ibb.co/gtSCz5r/Screenshot-2021-03-21-23-25-56-884-com-termux.jpg) when I did cut out.mkv ? İt did fix the malformed file I think?

## Edit:

> If you want to cut a video precisely you need to re-encode it.

Precisely cutting doesn't matter for me I do prefer -c copy lossless video and fast download. 
encoding would take a while

>If it helps, and it then plays normal, the script could always download 2 seconds earlier and then cut the 2 seconds again.

This could be good solution but 2 seconds doesn't seem to work lets try 3 or 4 seconds and if a problem again occurs then it seem like nothing can be done?
Then I think I will cut video manually myself.

**Comment by cvzi** [comment]
Yeah, I will change the script so it always downloads 5 seconds earlier and then cut 5 seconds again. Downloading 5 seconds more doesn't really matter, it takes not much time.

When it works, then I will also improve the download function in the script so that it downloads to a normal name and not always out.mkv

**Comment by erickyun** [comment]
> Yeah, I will change the script so it always downloads 5 seconds earlier and then cut 5 seconds again. Downloading 5 seconds more doesn't really matter, it takes not much time.
> 
> When it works, then I will also improve the download function in the script so that it downloads to a normal name and not always out.mkv

Could maybe adding this to ffmpeg help?

[avoid_negative_ts](https://ffmpeg.org/ffmpeg-all.html#:~:text=avoid_negative_ts%20integer%20%28output%29) help?

, adding [-seek_timestamp](https://ffmpeg.org/ffmpeg-all.html#:~:text=-seek_timestamp%20%28input%29)

Or -accurate_seek (input)

## Edit:
never mind didn't work. :(

**Comment by cvzi** [comment]
I changed both version, with slightly different commands:
https://github.com/cvzi/mpv-youtube-download/blob/timerange/youtube-download.lua
https://github.com/cvzi/mpv-youtube-download/blob/timerange2/youtube-download.lua

**Comment by erickyun** [comment]
> I changed both version, with slightly different commands:
> https://github.com/cvzi/mpv-youtube-download/blob/timerange/youtube-download.lua
> https://github.com/cvzi/mpv-youtube-download/blob/timerange2/youtube-download.lua

Yes not this [~version~](https://github.com/cvzi/mpv-youtube-download/blob/timerange/youtube-download.lua) but this [version](https://github.com/cvzi/mpv-youtube-download/blob/timerange2/youtube-download.lua) works perfectly 👍 
Thank you very much for this awesome script I really appreciate your work.🙂👍👍👍

**Comment by erickyun** [comment]
@cvzi 

sorry I was wrong it seems [timerange2](https://github.com/cvzi/mpv-youtube-download/blob/timerange2/youtube-download.lua) is better than timerange cuz audio is missing in the beginning(1 or 2 sec missing audio) of the video with this version so timerange2 should be prefered.

**But**
there is problem with timerange2.
 it does remove the downloaded video. I'm getting no file when I set **filename:** to desktop or any different location. 

İt only downloads in default location.  (mpv folder)

**Comment by cvzi** [comment]
I am working on it 🙂

Does the timerange version also have the problem with the filename/folder? Or only timerange2?

**Comment by erickyun** [comment]
> I am working on it 🙂

🙂👍

> Does the timerange version also have the problem with the filename/folder? Or only timerange2?

Only timerange2 has this problem.

**Comment by cvzi** [comment]
I changed the timerange version:
https://github.com/cvzi/mpv-youtube-download/blob/timerange/youtube-download.lua

**Comment by erickyun** [comment]
> I changed the timerange version:
> https://github.com/cvzi/mpv-youtube-download/blob/timerange/youtube-download.lua

But this version doesn't work right.
Video and audio are not synched.

**Comment by erickyun** [comment]
> I changed the timerange version:
> https://github.com/cvzi/mpv-youtube-download/blob/timerange/youtube-download.lua

@cvzi 

But this version doesn't work right.
Video and audio are not synched.

Could you only fix timerange2 filename?

**Comment by cvzi** [comment]
I think it should work now

**Comment by erickyun** [comment]
> I think it should work now

No it doesn't work. ☹️ the same problem occurs again not in sync. Cant hear audio for 3 or 4 seconds.

**Comment by cvzi** [comment]
Which one doesn't work now?

**Comment by erickyun** [comment]
> Which one doesn't work now?

I beginning to think this ytdl problem cuz external-args feature does have the same problem I think I will close the issue and try asking there. Btw thanks for fixing filename.
