### ISSUE TITLE
Arrow keys not captured in range mode if bound to other actions in `input.conf`

### ISSUE THREAD

**Issue by xfzv** [cvzi/mpv-youtube-download#31]
- mpv version: 0.36.0

I'm using `select_range_binding=ctrl+t` in `youtube-download.conf`.

`ctrl+t` works as expected: pressing it once opens the interval menu, pressing it again switches to fine tune mode, and one more time disables the range.

However, the arrow keys aren't doing anything, they still perform the mpv actions defined in `input.conf`.

Relevant keybindings in `input.conf`:

```
LEFT    seek -5
UP      no-osd add volume 1 ; script-binding uosc/flash-volume
DOWN    no-osd add volume -1 ; script-binding uosc/flash-volume
RIGHT   seek 5    #@click
RIGHT   script-binding evafast/speedup    #@press
RIGHT   script-binding evafast/slowdown   #@release
```

Disabling these keybindings solves the issue (the arrow keys work as expected in range mode).

**Comment by cvzi** [comment]
Possibly this can be solved by replacing `mp.add_key_binding` with [`mp.add_forced_key_binding`](https://mpv.io/manual/master/#lua-scripting-mp-add-forced-key-binding(-)) in these four lines:
https://github.com/cvzi/mpv-youtube-download/blob/161e7eb80287f4f8c8ff6add43b62226d91907a9/youtube-download.lua#L1099-L1102

**Comment by xfzv** [comment]
Thanks, the following works fine indeed:

```lua
mp.add_forced_key_binding("up", "select-range-set-up", select_range_set_end)
mp.add_forced_key_binding("down", "select-range-set-down", select_range_set_start)
mp.add_forced_key_binding("left", "select-range-set-left", select_range_set_left)
mp.add_forced_key_binding("right", "select-range-set-right", select_range_set_right)
```

**Comment by cvzi** [comment]
Thanks, I'll change the script when I have some time. 

Or if you like you can create a pull request with the changes.
