### ISSUE TITLE
Does this work with mpv.net ?

### ISSUE THREAD

**Issue by Vortexakhaj** [cvzi/mpv-youtube-download#5]
![image](https://user-images.githubusercontent.com/21369699/112457949-3dfa2280-8d82-11eb-819e-0e612ac76db3.png)

Doesnt load any key binding.

**Comment by cvzi** [comment]
I have no idea. I will test it later. Do you know if other scripts with key binding work in mpv.net?

**Comment by cvzi** [comment]
It seems the key binding does not work with mpv.net.

The keyboard shortcuts in the script and the .conf-file don't work with mpv.net.
You need to set the keyboard shortcuts yourself in your `input.conf`. Default location is `%APPDATA%\mpv.net\input.conf`.
Add the following lines to the end of your `input.conf` (change the keys if they are already used, leave out lines that you don't need):

```

 Ctrl+d     script-message-to   youtube_download   download-video
 Ctrl+a     script-message-to   youtube_download   download-audio
 Ctrl+s     script-message-to   youtube_download   download-subtitle
 Ctrl+i     script-message-to   youtube_download   download-embed-subtitle

```

**Comment by Vortexakhaj** [comment]
> It seems the key binding does not work with mpv.net.
> 
> The keyboard shortcuts in the script and the .conf-file don't work with mpv.net.
> You need to set the keyboard shortcuts yourself in your `input.conf`. Default location is `%APPDATA%\mpv.net\input.conf`.
> Add the following lines to the end of your `input.conf` (change the keys if they are already used, leave out lines that you don't need):
> 
> ```
> 
>  Ctrl+d     script-message-to   youtube_download   download-video
>  Ctrl+a     script-message-to   youtube_download   download-audio
>  Ctrl+s     script-message-to   youtube_download   download-subtitle
>  Ctrl+i     script-message-to   youtube_download   download-embed-subtitle
> ```

oh we has to use script-message-to i was using script_binding that why it was not working

**Comment by cvzi** [comment]
Does it work now?

**Comment by Vortexakhaj** [comment]
Yeah its works like a charm now. Thanks for the Help.
