### ISSUE TITLE
Please add functionality to download at currently loaded quality and at other qualities interactively.

### ISSUE THREAD

**Issue by StacktraceException** [cvzi/mpv-youtube-download#6]
As for now, there is no point in using this unless there is an interactive option to select the qualities with suboption to download the current ones.

I'd use it in a case of setting it to best quality always but...
There is no info of actually what file (quality) is being downloaded. These are the reasons, that until this is improved it's better to use the proper tool in the proper way.

Anyway I appreciate the effort :)

**Comment by cvzi** [comment]
It uses the default of youtube-dl (I think that is the best available video). You can set a quality for all downloads in the config section of the script: 
https://github.com/cvzi/mpv-youtube-download/blob/6743d746d382a9b407dbc3ffae0a245ad429039e/youtube-download.lua#L32-L34
for example: `video_format = "bestvideo+bestaudio", `

I can try to add an option to always download the current quality, that should be possible.

I don't think I will add interactive options for the quality, the purpose of this script is to have a quick way of downloading.

**Comment by cvzi** [comment]
I added the option to download the current format.
Set `video_format = "current",` and the script will always download the current quality.

If you have the [mpv-youtube-quality](https://github.com/jgreco/mpv-youtube-quality) script installed as well, you can press Ctrl+f, select a format interactively and then this script can download it with Ctrl+d
