### ISSUE TITLE
Add ability to cancel download.

### ISSUE THREAD

**Issue by emanrdesu** [cvzi/mpv-youtube-download#7]
I try to kill youtube-dl, but the process still continues, unless I exit mpv.

**Comment by cvzi** [comment]
I am not sure if this is possible, I will check

**Comment by cvzi** [comment]
I have added it. You can now press the key combinations twice to cancel a download. E.g. first time you press CTRL+d it starts to download, then you can press CTRL+d again and it will show "Download in progress. Press again to cancel download" and then you have to press a third time CTRL+d to actually cancel the download.

Can you please check if it works. I will probably not test or use this very much myself

**Comment by emanrdesu** [comment]
> I have added it. You can now press the key combinations twice to cancel a download. E.g. first time you press CTRL+d it starts to download, then you can press CTRL+d again and it will show "Download in progress. Press again to cancel download" and then you have to press a third time CTRL+d to actually cancel the download.
> 
> Can you please check if it works. I will probably not test or use this very much myself

Yes, it works, thank you.
As a final touch up, can you add a line to remove the partially downloaded file from the filesystem as well?

**Comment by cvzi** [comment]
I've changed it to remove the FILENAME.part file.
The problem is that youtube-dl does not report the name of the partial file, so the script just appends .part to the filename and tries to delete that file. I don't know if that will always work or if youtube-dl creates other partial files
