### ISSUE TITLE
[Feature Requests] Support for user configs, yt-dlp support, and support for non youtube urls

### ISSUE THREAD

**Issue by Anskrevy** [cvzi/mpv-youtube-download#8]
For the first request it would be nice to be able to specify a config file to be used for any of the key bindings. It wouldn't be required but an option to set ctrl+a to run, effectively, youtube-dl/yt-dlp --config-location /path/to/config $video. This should override any other options that the script tries to set to avoid conflicts. Users can specify tons of options in a config file that this script does not explicitly support. If this is not possible then I would ask if an option could be added to specify different directories for different download types. e.g. ctrl+a downloads to /path/to/dir1, ctrl+d downloads to /path/to/dir2, etc.
For the second request, please add support for yt-dlp as youtube-dl is looking like it is dead. I don't have this problem as I have yt-dlp symlinked to youtube-dl for this reason but others might not. 
And for the third request basically what it says. Maybe this is not possible but youtube-dl and yt-dlp both support far more options than just youtube urls.

This is really cool btw, and I'm glad I found it. Thanks for your work!

**Comment by cvzi** [comment]
If replacing `youtube-dl` with `yt-dlp` works with a symlink, than it should be easy to do the second thing in the script as well. Is `yt-dlp` generally better than `youtube-dl`? I don't really know anything about the difference.

**Comment by Anskrevy** [comment]
> Is `yt-dlp` generally better than `youtube-dl`? I don't really know anything about the difference.

youtube-dl hasn't had a new commit since June. yt-dlp is a fork of youtube-dl with additional features and fixes, as per their [github page](https://github.com/yt-dlp/yt-dlp). I would say it is generally better. I don't know every issue that youtube-dl has but one that seems prominent is bandwidth being throttled. It doesn't seem to happen with all users, but it is an issue that yt-dlp does not have, at least not as far as I know.

**Comment by cvzi** [comment]
Now the script will try to detect the executable in the following order:
`"yt-dlp", "youtube-dl", "yt-dlp_x86", "yt-dlp_macos", "yt-dlp_min", "yt-dlc"`
This is done on every start, but if you know you want to use `yt-dlp` you can hard code it in the config here:
https://github.com/cvzi/mpv-youtube-download/blob/67c3b5bb66b07ebdce123aa4ae551e54d36d2e90/youtube-download.lua#L82-L84
By setting this to
```lua
 youtube_dl_exe = "yt-dlp",
```

**Comment by cvzi** [comment]
Now the script runs on any url that starts with `https://`, `http://` or `ytdl://`

**Comment by cvzi** [comment]
You can now set a config file for any or all of the keyboard shortcuts. If it is set, it will run 
```bash
yt-dlp --config-location CONFIG_FILE VIDEO_URL
```

https://github.com/cvzi/mpv-youtube-download/blob/d1f2453d3e4ce56b4b9a5ff3ae069243e85f6417/youtube-download.lua#L87-L96

**Comment by Anskrevy** [comment]
10/10 brother. This is great!
