### ISSUE TITLE
download failed: ERROR: unable to open for writing: [Errno 13] Permission denied 

### ISSUE THREAD

**Issue by nobef** [cvzi/mpv-youtube-download#9]
Windows 11 
![изображение](https://user-images.githubusercontent.com/77186394/147363963-39ba1949-67a4-4e2c-9962-b6880d3592d2.png)
download failed: ERROR: unable to open for writing: [Errno 13] Permission denied

**Comment by cvzi** [comment]
I think this happens if mpv.exe or youtube-dl.exe are in a folder where it does not have permission to change a file.

You could try to change the download folder in the script:
https://github.com/cvzi/mpv-youtube-download/blob/67c3b5bb66b07ebdce123aa4ae551e54d36d2e90/youtube-download.lua#L69
For example change it to:
```lua
    filename = "C:\\Users\\YourWindowsUserName\\Downloads\\%(title)s.%(ext)s",
```

**Comment by nobef** [comment]
@cvzi 
By the way, I tried to change the directory of the downloaded file to D: / Downloads because I have a download folder there. Could this be the reason? But it did not download in the default state either.
  That is, the question: can there be an error if there is no such directory as indicated in the script?
  Ok thanks i will try
      
      
      -- Or "C:/Users/Username/Downloads/%(title)s.%(ext)s"

I tried to change this line to D: / Downloads

**Comment by cvzi** [comment]
Usually  `youtube-dl` creates the directory if it does not exist. I don't really know if D:/Downloads could be a problem (Also I don't have Windows 11).
You could try the youtube-dl command directly in a terminal, maybe there is a longer error message. The script just executes a command like this:
```
youtube-dl -o "D:/Users/USERNAME/Downloads/%(title)s.%(ext)s" "https://www.youtube.com/watch?v=ABCDEFG"
```
You can run it yourself in the Windows Terminal to check if it works.

**Comment by nobef** [comment]
@cvzi  This script on mpv works for me on debian. It downloads to windows from the console everywhere, only in mpv there is such an error. OK I'll try.

 yt-dlp*

**Comment by cvzi** [comment]
On my Windows 10, I can create the same error `Errno 13` if I select a directory where the script obviously has not rights. For example: `filename = "C:/Program Files/%(title)s.%(ext)s",`
Then I get:
```
ERROR: unable to open for writing: [Errno 13] Permission denied: 'C:\\Program Files\\THE_PRODIGY_-_90-.f248.webm.part'
```
This is ok, because `C:/Program Files/` is protected in Windows. 

But I don't understand why it would happen with a "normal" directory

**Comment by nobef** [comment]
@cvzi
 I have yt-dlp in C:/Temp
ffmpeg to C:/ffmpeg
mpv installed in C:/Program/MPV
Python 3.10 in C:/Python


Is the picture correct?
![изображение](https://user-images.githubusercontent.com/77186394/147408713-89c7525a-7246-4e23-b247-e449ac77b69f.png)

 
Usually downloads from the console to C:\Users\username

**Comment by cvzi** [comment]
If you use a shortcut to open mpv, you could try to set the "Start in" directory/working directory to a different folder.
For example set it to `D:\Downloads\`

![startin](https://user-images.githubusercontent.com/8470684/147505110-bc39a697-3ab6-40b7-a2e5-8c2f5c18e25a.png)

**Comment by nobef** [comment]
@cvzi Yes, we managed to download it this way. Updated the icon on the taskbar - it also works. For now

**Comment by cvzi** [comment]
I will leave this issue open for other people, but I don't see a better solution for this problem. 
A warning message will now be shown by the script if mpv.exe runs under "C:/Program Files" and the "filename" was not changed to a different directory.

**Comment by nobef** [comment]
@cvzi That helped!
![изображение](https://user-images.githubusercontent.com/77186394/162968442-1c444bea-82d7-47ca-bfdd-4f96c5742dbd.png)
